# Generated by Django 4.1.7 on 2023-03-02 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bid_comment_listing_watchlist_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="listingid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auctions.listing"
            ),
        ),
    ]
